// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/peak.dart';
import 'models/tasmap50k.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6887978098338940139),
    name: 'Peak',
    lastPropertyId: const obx_int.IdUid(6, 8968330069070174548),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8477524303206664798),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2823209193653409857),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2345462672031361859),
        name: 'elevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3823448150973689218),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2864945409495793627),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8968330069070174548),
        name: 'area',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1328676866860602429),
    name: 'Tasmap50k',
    lastPropertyId: const obx_int.IdUid(16, 6317855365936723768),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1561892639929499429),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2660682564703842058),
        name: 'series',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7309767395043469174),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 223135285092675213),
        name: 'parentSeries',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1357329744860573277),
        name: 'mgrs100kIds',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2617068777301457671),
        name: 'eastingMin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2093783745225202890),
        name: 'eastingMax',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5090738047943149597),
        name: 'northingMin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7244678684225968530),
        name: 'northingMax',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1016025314984462614),
        name: 'mgrsMid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5528747832735759740),
        name: 'eastingMid',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5455427650142993126),
        name: 'northingMid',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7214738622216751167),
        name: 'tl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3206417400481328273),
        name: 'tr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5789058894498647677),
        name: 'bl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6317855365936723768),
        name: 'br',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 1328676866860602429),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Peak: obx_int.EntityDefinition<Peak>(
      model: _entities[0],
      toOneRelations: (Peak object) => [],
      toManyRelations: (Peak object) => {},
      getId: (Peak object) => object.id,
      setId: (Peak object, int id) {
        object.id = id;
      },
      objectToFB: (Peak object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final areaOffset = object.area == null
            ? null
            : fbb.writeString(object.area!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.elevation);
        fbb.addFloat64(3, object.latitude);
        fbb.addFloat64(4, object.longitude);
        fbb.addOffset(5, areaOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final elevationParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final areaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = Peak(
          id: idParam,
          name: nameParam,
          elevation: elevationParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          area: areaParam,
        );

        return object;
      },
    ),
    Tasmap50k: obx_int.EntityDefinition<Tasmap50k>(
      model: _entities[1],
      toOneRelations: (Tasmap50k object) => [],
      toManyRelations: (Tasmap50k object) => {},
      getId: (Tasmap50k object) => object.id,
      setId: (Tasmap50k object, int id) {
        object.id = id;
      },
      objectToFB: (Tasmap50k object, fb.Builder fbb) {
        final seriesOffset = fbb.writeString(object.series);
        final nameOffset = fbb.writeString(object.name);
        final parentSeriesOffset = fbb.writeString(object.parentSeries);
        final mgrs100kIdsOffset = fbb.writeString(object.mgrs100kIds);
        final mgrsMidOffset = fbb.writeString(object.mgrsMid);
        final tlOffset = fbb.writeString(object.tl);
        final trOffset = fbb.writeString(object.tr);
        final blOffset = fbb.writeString(object.bl);
        final brOffset = fbb.writeString(object.br);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, seriesOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, parentSeriesOffset);
        fbb.addOffset(4, mgrs100kIdsOffset);
        fbb.addInt64(5, object.eastingMin);
        fbb.addInt64(6, object.eastingMax);
        fbb.addInt64(7, object.northingMin);
        fbb.addInt64(8, object.northingMax);
        fbb.addOffset(9, mgrsMidOffset);
        fbb.addInt64(10, object.eastingMid);
        fbb.addInt64(11, object.northingMid);
        fbb.addOffset(12, tlOffset);
        fbb.addOffset(13, trOffset);
        fbb.addOffset(14, blOffset);
        fbb.addOffset(15, brOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final seriesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final parentSeriesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final mgrs100kIdsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final eastingMinParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final eastingMaxParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final northingMinParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final northingMaxParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final mgrsMidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final eastingMidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final northingMidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final tlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final trParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final blParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final brParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final object = Tasmap50k(
          id: idParam,
          series: seriesParam,
          name: nameParam,
          parentSeries: parentSeriesParam,
          mgrs100kIds: mgrs100kIdsParam,
          eastingMin: eastingMinParam,
          eastingMax: eastingMaxParam,
          northingMin: northingMinParam,
          northingMax: northingMaxParam,
          mgrsMid: mgrsMidParam,
          eastingMid: eastingMidParam,
          northingMid: northingMidParam,
          tl: tlParam,
          tr: trParam,
          bl: blParam,
          br: brParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Peak] entity fields to define ObjectBox queries.
class Peak_ {
  /// See [Peak.id].
  static final id = obx.QueryIntegerProperty<Peak>(_entities[0].properties[0]);

  /// See [Peak.name].
  static final name = obx.QueryStringProperty<Peak>(_entities[0].properties[1]);

  /// See [Peak.elevation].
  static final elevation = obx.QueryDoubleProperty<Peak>(
    _entities[0].properties[2],
  );

  /// See [Peak.latitude].
  static final latitude = obx.QueryDoubleProperty<Peak>(
    _entities[0].properties[3],
  );

  /// See [Peak.longitude].
  static final longitude = obx.QueryDoubleProperty<Peak>(
    _entities[0].properties[4],
  );

  /// See [Peak.area].
  static final area = obx.QueryStringProperty<Peak>(_entities[0].properties[5]);
}

/// [Tasmap50k] entity fields to define ObjectBox queries.
class Tasmap50k_ {
  /// See [Tasmap50k.id].
  static final id = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[0],
  );

  /// See [Tasmap50k.series].
  static final series = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[1],
  );

  /// See [Tasmap50k.name].
  static final name = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[2],
  );

  /// See [Tasmap50k.parentSeries].
  static final parentSeries = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[3],
  );

  /// See [Tasmap50k.mgrs100kIds].
  static final mgrs100kIds = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[4],
  );

  /// See [Tasmap50k.eastingMin].
  static final eastingMin = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[5],
  );

  /// See [Tasmap50k.eastingMax].
  static final eastingMax = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[6],
  );

  /// See [Tasmap50k.northingMin].
  static final northingMin = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[7],
  );

  /// See [Tasmap50k.northingMax].
  static final northingMax = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[8],
  );

  /// See [Tasmap50k.mgrsMid].
  static final mgrsMid = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[9],
  );

  /// See [Tasmap50k.eastingMid].
  static final eastingMid = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[10],
  );

  /// See [Tasmap50k.northingMid].
  static final northingMid = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[11],
  );

  /// See [Tasmap50k.tl].
  static final tl = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[12],
  );

  /// See [Tasmap50k.tr].
  static final tr = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[13],
  );

  /// See [Tasmap50k.bl].
  static final bl = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[14],
  );

  /// See [Tasmap50k.br].
  static final br = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[15],
  );
}
