// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/gpx_track.dart';
import 'models/peak.dart';
import 'models/peak_list.dart';
import 'models/peaks_bagged.dart';
import 'models/route.dart';
import 'models/route_graph_chunk.dart';
import 'models/route_graph_manifest.dart';
import 'models/route_graph_trail_display_chunk.dart';
import 'models/route_graph_way_index.dart';
import 'models/tasmap50k.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6887978098338940139),
    name: 'Peak',
    lastPropertyId: const obx_int.IdUid(19, 6639928261090114468),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8477524303206664798),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2823209193653409857),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2345462672031361859),
        name: 'elevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3823448150973689218),
        name: 'latitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2864945409495793627),
        name: 'longitude',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8968330069070174548),
        name: 'region',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3446234006847826756),
        name: 'gridZoneDesignator',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8664681880697364013),
        name: 'mgrs100kId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7732389157431803637),
        name: 'easting',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8739282244333038063),
        name: 'northing',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1046675984660509866),
        name: 'osmId',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 1646709204047143715),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 809639103704790338),
        name: 'sourceOfTruth',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2166216577181347171),
        name: 'altName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8569973600435793379),
        name: 'verified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2976348997316740754),
        name: 'peakbaggerPid',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8603710331303678704),
        name: 'prominence',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3150687822589368084),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2633572753115612143),
        name: 'county',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 6639928261090114468),
        name: 'range',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1328676866860602429),
    name: 'Tasmap50k',
    lastPropertyId: const obx_int.IdUid(28, 82954956939637119),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1561892639929499429),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2660682564703842058),
        name: 'series',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7309767395043469174),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 223135285092675213),
        name: 'parentSeries',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1357329744860573277),
        name: 'mgrs100kIds',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2617068777301457671),
        name: 'eastingMin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2093783745225202890),
        name: 'eastingMax',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5090738047943149597),
        name: 'northingMin',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7244678684225968530),
        name: 'northingMax',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1016025314984462614),
        name: 'mgrsMid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5528747832735759740),
        name: 'eastingMid',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5455427650142993126),
        name: 'northingMid',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3630802638893046338),
        name: 'p1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 7626547087832084302),
        name: 'p2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 3107002462381362263),
        name: 'p3',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 5743465403652482584),
        name: 'p4',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6157314611976741618),
        name: 'p5',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 5268849250419803411),
        name: 'p6',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 2057491973401598098),
        name: 'p7',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 3816548390083327168),
        name: 'p8',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 3234303295083208156),
        name: 'p9',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 5493574876011783287),
        name: 'p10',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 9118170653524728884),
        name: 'p11',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 82954956939637119),
        name: 'p12',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8449374379554926112),
    name: 'GpxTrack',
    lastPropertyId: const obx_int.IdUid(36, 6865718623478699060),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2055590878041962616),
        name: 'gpxTrackId',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6692349517233010448),
        name: 'trackName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8088153468164546543),
        name: 'startDateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4876941213384233127),
        name: 'ascent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2097315354030142327),
        name: 'totalTimeMillis',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2827267495073081727),
        name: 'trackColour',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5063544268903792566),
        name: 'contentHash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1215055040594058915),
        name: 'trackDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6504873653632491140),
        name: 'endDateTime',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8803569488989977927),
        name: 'gpxFile',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 9193806285716622041),
        name: 'displayTrackPointsByZoom',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3158897785574741819),
        name: 'distanceToPeak',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4676893102821713845),
        name: 'distanceFromPeak',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3002355459907763344),
        name: 'lowestElevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2083444332056874121),
        name: 'highestElevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 9126160852790576644),
        name: 'distance2d',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 3901365715486408203),
        name: 'distance3d',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 4581494205528903333),
        name: 'descent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 371950216447848570),
        name: 'startElevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 6478259269495091022),
        name: 'endElevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 8336839992000669416),
        name: 'elevationProfile',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 2608880238551491510),
        name: 'filteredTrack',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 3742941563149370755),
        name: 'peakCorrelationProcessed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 5865563897202447528),
        name: 'movingTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 7278287822454877677),
        name: 'restingTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 3001004799159620060),
        name: 'pausedTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 7984434964772208297),
        name: 'gpxFileRepaired',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 5662316491761993386),
        name: 'visible',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 7180206158243649018),
        name: 'averageSpeedKmh',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 3034155260083667586),
        name: 'movingSpeedKmh',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(36, 6865718623478699060),
        name: 'maxSpeedKmh',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 8194382659905112901),
        name: 'peaks',
        targetId: const obx_int.IdUid(1, 6887978098338940139),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5754024077279183606),
    name: 'PeakList',
    lastPropertyId: const obx_int.IdUid(4, 1234567890123456789),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2582678945515018062),
        name: 'peakListId',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 820297320693406618),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 7211080441040466135),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6714151057753537882),
        name: 'peakList',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1234567890123456789),
        name: 'region',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 9023966399287465849),
    name: 'PeaksBagged',
    lastPropertyId: const obx_int.IdUid(4, 1625516356902882927),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 187546268832463095),
        name: 'baggedId',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6205008261349276758),
        name: 'peakId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5251465697122538351),
        name: 'gpxId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1625516356902882927),
        name: 'date',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 3506540890240152030),
    name: 'Route',
    lastPropertyId: const obx_int.IdUid(16, 8462861869933376021),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2188231076669519255),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1411349293898722170),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1535979703523787788),
        name: 'displayRoutePointsByZoom',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6017809366811028685),
        name: 'colour',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5315881796693193560),
        name: 'distance2d',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2208974196016124072),
        name: 'distance3d',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 9200665486370958132),
        name: 'ascent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6577824166279808829),
        name: 'descent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2538669739041613493),
        name: 'startElevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5427729360856529099),
        name: 'endElevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7531847065936996502),
        name: 'lowestElevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1477644722764121334),
        name: 'highestElevation',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8747517438538908610),
        name: 'gpxRouteJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6508459819772890067),
        name: 'routeWaypointsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7267278234167446456),
        name: 'desc',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8462861869933376021),
        name: 'visible',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 596705519527760639),
    name: 'RouteGraphChunk',
    lastPropertyId: const obx_int.IdUid(10, 3398479501893264143),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1469808838581828297),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1793741707318597188),
        name: 'recordKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 2629505412358106755),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6967455734301465955),
        name: 'chunkKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7872400213766686598),
        name: 'generation',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4727494534911280573),
        name: 'minLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8640538855355177463),
        name: 'minLon',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5465738688593217615),
        name: 'maxLat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7005453871542192813),
        name: 'maxLon',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6216780808421857277),
        name: 'elementCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3398479501893264143),
        name: 'payloadJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 1444775778480771967),
    name: 'RouteGraphManifest',
    lastPropertyId: const obx_int.IdUid(10, 8758350155907503563),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2436359711993750832),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6092638898341522512),
        name: 'sourceHash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7324269441776161543),
        name: 'schemaVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4707116018081072653),
        name: 'activeGeneration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4633208416782374128),
        name: 'importedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6538104877462276138),
        name: 'chunkCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7093348560738932483),
        name: 'nodeCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2221664074292599462),
        name: 'edgeCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7697351082653749625),
        name: 'readinessState',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8758350155907503563),
        name: 'lastError',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 7206587872972155691),
    name: 'RouteGraphWayIndex',
    lastPropertyId: const obx_int.IdUid(16, 8218973595292904004),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 443872081856852457),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8740285009668479209),
        name: 'recordKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(4, 6245894765064343651),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7771898020658441888),
        name: 'generation',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(5, 5438526232553354638),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2107571599242027657),
        name: 'chunkKey',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 4453574097210365444),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5624145145932228172),
        name: 'osmWayId',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(7, 8874830724970828136),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 232566106986568028),
        name: 'highway',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 6870510557970833435),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6609313452380556519),
        name: 'surface',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 5425780077425005528),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3016050586232872511),
        name: 'footway',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 8396615452003065703),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2575002113050661287),
        name: 'foot',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(11, 7369659444779405127),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1283776695175041702),
        name: 'route',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 1484381592932965134),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2636483900223481184),
        name: 'access',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(13, 6657326188302950051),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5542982211169047235),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 7822155739681887078),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5910877470453541317),
        name: 'normalizedName',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(15, 7055560742538121566),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7913366029637209172),
        name: 'lengthMeters',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(16, 9056274443209376134),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 9004938176759168094),
        name: 'tagCount',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(17, 6932016565344639744),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8218973595292904004),
        name: 'tagsJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 6059948320416146250),
    name: 'RouteGraphTrailDisplayChunk',
    lastPropertyId: const obx_int.IdUid(6, 7689183445842674669),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4554691679847495489),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3068832968782807046),
        name: 'recordKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(18, 1118203870652404234),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5073002466263635198),
        name: 'generation',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(19, 8396529678208824924),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3986380455666052632),
        name: 'cacheZoom',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(20, 8805275054975868171),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5320267107048684954),
        name: 'chunkKey',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(21, 5356499526039797575),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7689183445842674669),
        name: 'payloadJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 6059948320416146250),
    lastIndexId: const obx_int.IdUid(21, 5356499526039797575),
    lastRelationId: const obx_int.IdUid(1, 8194382659905112901),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      3390857021483670935,
      3580443233466692573,
      3658721134433213764,
      7214738622216751167,
      3206417400481328273,
      5789058894498647677,
      6317855365936723768,
      4814077432237599816,
      1741998931807441846,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Peak: obx_int.EntityDefinition<Peak>(
      model: _entities[0],
      toOneRelations: (Peak object) => [],
      toManyRelations: (Peak object) => {},
      getId: (Peak object) => object.id,
      setId: (Peak object, int id) {
        object.id = id;
      },
      objectToFB: (Peak object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final regionOffset = object.region == null
            ? null
            : fbb.writeString(object.region!);
        final gridZoneDesignatorOffset = fbb.writeString(
          object.gridZoneDesignator,
        );
        final mgrs100kIdOffset = fbb.writeString(object.mgrs100kId);
        final eastingOffset = fbb.writeString(object.easting);
        final northingOffset = fbb.writeString(object.northing);
        final sourceOfTruthOffset = fbb.writeString(object.sourceOfTruth);
        final altNameOffset = fbb.writeString(object.altName);
        final countryOffset = fbb.writeString(object.country);
        final countyOffset = fbb.writeString(object.county);
        final rangeOffset = fbb.writeString(object.range);
        fbb.startTable(20);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(2, object.elevation);
        fbb.addFloat64(3, object.latitude);
        fbb.addFloat64(4, object.longitude);
        fbb.addOffset(5, regionOffset);
        fbb.addOffset(6, gridZoneDesignatorOffset);
        fbb.addOffset(7, mgrs100kIdOffset);
        fbb.addOffset(8, eastingOffset);
        fbb.addOffset(9, northingOffset);
        fbb.addInt64(10, object.osmId);
        fbb.addOffset(11, sourceOfTruthOffset);
        fbb.addOffset(12, altNameOffset);
        fbb.addBool(13, object.verified);
        fbb.addInt64(14, object.peakbaggerPid);
        fbb.addFloat64(15, object.prominence);
        fbb.addOffset(16, countryOffset);
        fbb.addOffset(17, countyOffset);
        fbb.addOffset(18, rangeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final osmIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final peakbaggerPidParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final altNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final elevationParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final prominenceParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final countyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final rangeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 40, '');
        final latitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final longitudeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final regionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final gridZoneDesignatorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final mgrs100kIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final eastingParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final northingParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final verifiedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final sourceOfTruthParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final object = Peak(
          id: idParam,
          osmId: osmIdParam,
          peakbaggerPid: peakbaggerPidParam,
          name: nameParam,
          altName: altNameParam,
          elevation: elevationParam,
          prominence: prominenceParam,
          country: countryParam,
          county: countyParam,
          range: rangeParam,
          latitude: latitudeParam,
          longitude: longitudeParam,
          region: regionParam,
          gridZoneDesignator: gridZoneDesignatorParam,
          mgrs100kId: mgrs100kIdParam,
          easting: eastingParam,
          northing: northingParam,
          verified: verifiedParam,
          sourceOfTruth: sourceOfTruthParam,
        );

        return object;
      },
    ),
    Tasmap50k: obx_int.EntityDefinition<Tasmap50k>(
      model: _entities[1],
      toOneRelations: (Tasmap50k object) => [],
      toManyRelations: (Tasmap50k object) => {},
      getId: (Tasmap50k object) => object.id,
      setId: (Tasmap50k object, int id) {
        object.id = id;
      },
      objectToFB: (Tasmap50k object, fb.Builder fbb) {
        final seriesOffset = fbb.writeString(object.series);
        final nameOffset = fbb.writeString(object.name);
        final parentSeriesOffset = fbb.writeString(object.parentSeries);
        final mgrs100kIdsOffset = fbb.writeString(object.mgrs100kIds);
        final mgrsMidOffset = fbb.writeString(object.mgrsMid);
        final p1Offset = fbb.writeString(object.p1);
        final p2Offset = fbb.writeString(object.p2);
        final p3Offset = fbb.writeString(object.p3);
        final p4Offset = fbb.writeString(object.p4);
        final p5Offset = fbb.writeString(object.p5);
        final p6Offset = fbb.writeString(object.p6);
        final p7Offset = fbb.writeString(object.p7);
        final p8Offset = fbb.writeString(object.p8);
        final p9Offset = fbb.writeString(object.p9);
        final p10Offset = fbb.writeString(object.p10);
        final p11Offset = fbb.writeString(object.p11);
        final p12Offset = fbb.writeString(object.p12);
        fbb.startTable(29);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, seriesOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, parentSeriesOffset);
        fbb.addOffset(4, mgrs100kIdsOffset);
        fbb.addInt64(5, object.eastingMin);
        fbb.addInt64(6, object.eastingMax);
        fbb.addInt64(7, object.northingMin);
        fbb.addInt64(8, object.northingMax);
        fbb.addOffset(9, mgrsMidOffset);
        fbb.addInt64(10, object.eastingMid);
        fbb.addInt64(11, object.northingMid);
        fbb.addOffset(16, p1Offset);
        fbb.addOffset(17, p2Offset);
        fbb.addOffset(18, p3Offset);
        fbb.addOffset(19, p4Offset);
        fbb.addOffset(20, p5Offset);
        fbb.addOffset(21, p6Offset);
        fbb.addOffset(22, p7Offset);
        fbb.addOffset(23, p8Offset);
        fbb.addOffset(24, p9Offset);
        fbb.addOffset(25, p10Offset);
        fbb.addOffset(26, p11Offset);
        fbb.addOffset(27, p12Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final seriesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final parentSeriesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final mgrs100kIdsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final eastingMinParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final eastingMaxParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final northingMinParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final northingMaxParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final mgrsMidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final eastingMidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final northingMidParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final p1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final p2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final p3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 40, '');
        final p4Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 42, '');
        final p5Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 44, '');
        final p6Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 46, '');
        final p7Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 48, '');
        final p8Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 50, '');
        final p9Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 52, '');
        final p10Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 54, '');
        final p11Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 56, '');
        final p12Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 58, '');
        final object = Tasmap50k(
          id: idParam,
          series: seriesParam,
          name: nameParam,
          parentSeries: parentSeriesParam,
          mgrs100kIds: mgrs100kIdsParam,
          eastingMin: eastingMinParam,
          eastingMax: eastingMaxParam,
          northingMin: northingMinParam,
          northingMax: northingMaxParam,
          mgrsMid: mgrsMidParam,
          eastingMid: eastingMidParam,
          northingMid: northingMidParam,
          p1: p1Param,
          p2: p2Param,
          p3: p3Param,
          p4: p4Param,
          p5: p5Param,
          p6: p6Param,
          p7: p7Param,
          p8: p8Param,
          p9: p9Param,
          p10: p10Param,
          p11: p11Param,
          p12: p12Param,
        );

        return object;
      },
    ),
    GpxTrack: obx_int.EntityDefinition<GpxTrack>(
      model: _entities[2],
      toOneRelations: (GpxTrack object) => [],
      toManyRelations: (GpxTrack object) => {
        obx_int.RelInfo<GpxTrack>.toMany(1, object.gpxTrackId): object.peaks,
      },
      getId: (GpxTrack object) => object.gpxTrackId,
      setId: (GpxTrack object, int id) {
        object.gpxTrackId = id;
      },
      objectToFB: (GpxTrack object, fb.Builder fbb) {
        final trackNameOffset = fbb.writeString(object.trackName);
        final contentHashOffset = fbb.writeString(object.contentHash);
        final gpxFileOffset = fbb.writeString(object.gpxFile);
        final displayTrackPointsByZoomOffset = fbb.writeString(
          object.displayTrackPointsByZoom,
        );
        final elevationProfileOffset = fbb.writeString(object.elevationProfile);
        final filteredTrackOffset = fbb.writeString(object.filteredTrack);
        final gpxFileRepairedOffset = fbb.writeString(object.gpxFileRepaired);
        fbb.startTable(37);
        fbb.addInt64(0, object.gpxTrackId);
        fbb.addOffset(2, trackNameOffset);
        fbb.addInt64(3, object.startDateTime?.millisecondsSinceEpoch);
        fbb.addFloat64(5, object.ascent);
        fbb.addInt64(6, object.totalTimeMillis);
        fbb.addInt64(7, object.trackColour);
        fbb.addOffset(9, contentHashOffset);
        fbb.addInt64(10, object.trackDate?.millisecondsSinceEpoch);
        fbb.addInt64(11, object.endDateTime?.millisecondsSinceEpoch);
        fbb.addOffset(12, gpxFileOffset);
        fbb.addOffset(13, displayTrackPointsByZoomOffset);
        fbb.addFloat64(14, object.distanceToPeak);
        fbb.addFloat64(15, object.distanceFromPeak);
        fbb.addFloat64(16, object.lowestElevation);
        fbb.addFloat64(17, object.highestElevation);
        fbb.addFloat64(18, object.distance2d);
        fbb.addFloat64(19, object.distance3d);
        fbb.addFloat64(20, object.descent);
        fbb.addFloat64(21, object.startElevation);
        fbb.addFloat64(22, object.endElevation);
        fbb.addOffset(23, elevationProfileOffset);
        fbb.addOffset(24, filteredTrackOffset);
        fbb.addBool(25, object.peakCorrelationProcessed);
        fbb.addInt64(26, object.movingTime);
        fbb.addInt64(27, object.restingTime);
        fbb.addInt64(28, object.pausedTime);
        fbb.addOffset(29, gpxFileRepairedOffset);
        fbb.addBool(32, object.visible);
        fbb.addFloat64(33, object.averageSpeedKmh);
        fbb.addFloat64(34, object.movingSpeedKmh);
        fbb.addFloat64(35, object.maxSpeedKmh);
        fbb.finish(fbb.endTable());
        return object.gpxTrackId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startDateTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final trackDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final endDateTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final gpxTrackIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final contentHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final trackNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final trackDateParam = trackDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(trackDateValue, isUtc: true);
        final gpxFileParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final gpxFileRepairedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 62, '');
        final filteredTrackParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 52, '');
        final displayTrackPointsByZoomParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final startDateTimeParam = startDateTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                startDateTimeValue,
                isUtc: true,
              );
        final endDateTimeParam = endDateTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                endDateTimeValue,
                isUtc: true,
              );
        final distance2dParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          40,
          0,
        );
        final distance3dParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        final distanceToPeakParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final distanceFromPeakParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final lowestElevationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final highestElevationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final descentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          44,
          0,
        );
        final startElevationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          46,
          0,
        );
        final endElevationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          48,
          0,
        );
        final elevationProfileParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 50, '');
        final ascentParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final totalTimeMillisParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final movingTimeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          56,
        );
        final restingTimeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          58,
        );
        final pausedTimeParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          60,
        );
        final averageSpeedKmhParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          70,
          0,
        );
        final movingSpeedKmhParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          72,
          0,
        );
        final maxSpeedKmhParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          74,
          0,
        );
        final trackColourParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final visibleParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          68,
          false,
        );
        final peakCorrelationProcessedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          54,
          false,
        );
        final object = GpxTrack(
          gpxTrackId: gpxTrackIdParam,
          contentHash: contentHashParam,
          trackName: trackNameParam,
          trackDate: trackDateParam,
          gpxFile: gpxFileParam,
          gpxFileRepaired: gpxFileRepairedParam,
          filteredTrack: filteredTrackParam,
          displayTrackPointsByZoom: displayTrackPointsByZoomParam,
          startDateTime: startDateTimeParam,
          endDateTime: endDateTimeParam,
          distance2d: distance2dParam,
          distance3d: distance3dParam,
          distanceToPeak: distanceToPeakParam,
          distanceFromPeak: distanceFromPeakParam,
          lowestElevation: lowestElevationParam,
          highestElevation: highestElevationParam,
          descent: descentParam,
          startElevation: startElevationParam,
          endElevation: endElevationParam,
          elevationProfile: elevationProfileParam,
          ascent: ascentParam,
          totalTimeMillis: totalTimeMillisParam,
          movingTime: movingTimeParam,
          restingTime: restingTimeParam,
          pausedTime: pausedTimeParam,
          averageSpeedKmh: averageSpeedKmhParam,
          movingSpeedKmh: movingSpeedKmhParam,
          maxSpeedKmh: maxSpeedKmhParam,
          trackColour: trackColourParam,
          visible: visibleParam,
          peakCorrelationProcessed: peakCorrelationProcessedParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<GpxTrack>(
          object.peaks,
          store,
          obx_int.RelInfo<GpxTrack>.toMany(1, object.gpxTrackId),
        );
        return object;
      },
    ),
    PeakList: obx_int.EntityDefinition<PeakList>(
      model: _entities[3],
      toOneRelations: (PeakList object) => [],
      toManyRelations: (PeakList object) => {},
      getId: (PeakList object) => object.peakListId,
      setId: (PeakList object, int id) {
        object.peakListId = id;
      },
      objectToFB: (PeakList object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final peakListOffset = fbb.writeString(object.peakList);
        final regionOffset = fbb.writeString(object.region);
        fbb.startTable(5);
        fbb.addInt64(0, object.peakListId);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, peakListOffset);
        fbb.addOffset(3, regionOffset);
        fbb.finish(fbb.endTable());
        return object.peakListId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final peakListIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final peakListParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final regionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, Peak.defaultRegion);
        final object = PeakList(
          peakListId: peakListIdParam,
          name: nameParam,
          peakList: peakListParam,
          region: regionParam,
        );

        return object;
      },
    ),
    PeaksBagged: obx_int.EntityDefinition<PeaksBagged>(
      model: _entities[4],
      toOneRelations: (PeaksBagged object) => [],
      toManyRelations: (PeaksBagged object) => {},
      getId: (PeaksBagged object) => object.baggedId,
      setId: (PeaksBagged object, int id) {
        object.baggedId = id;
      },
      objectToFB: (PeaksBagged object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.baggedId);
        fbb.addInt64(1, object.peakId);
        fbb.addInt64(2, object.gpxId);
        fbb.addInt64(3, object.date?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.baggedId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final baggedIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final peakIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final gpxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final dateParam = dateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(dateValue, isUtc: true);
        final object = PeaksBagged(
          baggedId: baggedIdParam,
          peakId: peakIdParam,
          gpxId: gpxIdParam,
          date: dateParam,
        );

        return object;
      },
    ),
    Route: obx_int.EntityDefinition<Route>(
      model: _entities[5],
      toOneRelations: (Route object) => [],
      toManyRelations: (Route object) => {},
      getId: (Route object) => object.id,
      setId: (Route object, int id) {
        object.id = id;
      },
      objectToFB: (Route object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final displayRoutePointsByZoomOffset = fbb.writeString(
          object.displayRoutePointsByZoom,
        );
        final gpxRouteJsonOffset = fbb.writeString(object.gpxRouteJson);
        final routeWaypointsJsonOffset = fbb.writeString(
          object.routeWaypointsJson,
        );
        final descOffset = fbb.writeString(object.desc);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, displayRoutePointsByZoomOffset);
        fbb.addInt64(3, object.colour);
        fbb.addFloat64(4, object.distance2d);
        fbb.addFloat64(5, object.distance3d);
        fbb.addFloat64(6, object.ascent);
        fbb.addFloat64(7, object.descent);
        fbb.addFloat64(8, object.startElevation);
        fbb.addFloat64(9, object.endElevation);
        fbb.addFloat64(10, object.lowestElevation);
        fbb.addFloat64(11, object.highestElevation);
        fbb.addOffset(12, gpxRouteJsonOffset);
        fbb.addOffset(13, routeWaypointsJsonOffset);
        fbb.addOffset(14, descOffset);
        fbb.addBool(15, object.visible);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final displayRoutePointsByZoomParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final colourParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final visibleParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          34,
          false,
        );
        final distance2dParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final distance3dParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final ascentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final descentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final startElevationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final endElevationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final lowestElevationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final highestElevationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final object =
            Route(
                id: idParam,
                name: nameParam,
                desc: descParam,
                displayRoutePointsByZoom: displayRoutePointsByZoomParam,
                colour: colourParam,
                visible: visibleParam,
                distance2d: distance2dParam,
                distance3d: distance3dParam,
                ascent: ascentParam,
                descent: descentParam,
                startElevation: startElevationParam,
                endElevation: endElevationParam,
                lowestElevation: lowestElevationParam,
                highestElevation: highestElevationParam,
              )
              ..gpxRouteJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 28, '')
              ..routeWaypointsJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 30, '');

        return object;
      },
    ),
    RouteGraphChunk: obx_int.EntityDefinition<RouteGraphChunk>(
      model: _entities[6],
      toOneRelations: (RouteGraphChunk object) => [],
      toManyRelations: (RouteGraphChunk object) => {},
      getId: (RouteGraphChunk object) => object.id,
      setId: (RouteGraphChunk object, int id) {
        object.id = id;
      },
      objectToFB: (RouteGraphChunk object, fb.Builder fbb) {
        final recordKeyOffset = fbb.writeString(object.recordKey);
        final chunkKeyOffset = fbb.writeString(object.chunkKey);
        final payloadJsonOffset = fbb.writeString(object.payloadJson);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, recordKeyOffset);
        fbb.addOffset(2, chunkKeyOffset);
        fbb.addInt64(3, object.generation);
        fbb.addFloat64(4, object.minLat);
        fbb.addFloat64(5, object.minLon);
        fbb.addFloat64(6, object.maxLat);
        fbb.addFloat64(7, object.maxLon);
        fbb.addInt64(8, object.elementCount);
        fbb.addOffset(9, payloadJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final recordKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final chunkKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final generationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final minLatParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final minLonParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final maxLatParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final maxLonParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final elementCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final payloadJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final object = RouteGraphChunk(
          id: idParam,
          recordKey: recordKeyParam,
          chunkKey: chunkKeyParam,
          generation: generationParam,
          minLat: minLatParam,
          minLon: minLonParam,
          maxLat: maxLatParam,
          maxLon: maxLonParam,
          elementCount: elementCountParam,
          payloadJson: payloadJsonParam,
        );

        return object;
      },
    ),
    RouteGraphManifest: obx_int.EntityDefinition<RouteGraphManifest>(
      model: _entities[7],
      toOneRelations: (RouteGraphManifest object) => [],
      toManyRelations: (RouteGraphManifest object) => {},
      getId: (RouteGraphManifest object) => object.id,
      setId: (RouteGraphManifest object, int id) {
        object.id = id;
      },
      objectToFB: (RouteGraphManifest object, fb.Builder fbb) {
        final sourceHashOffset = fbb.writeString(object.sourceHash);
        final schemaVersionOffset = fbb.writeString(object.schemaVersion);
        final readinessStateOffset = fbb.writeString(object.readinessState);
        final lastErrorOffset = object.lastError == null
            ? null
            : fbb.writeString(object.lastError!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sourceHashOffset);
        fbb.addOffset(2, schemaVersionOffset);
        fbb.addInt64(3, object.activeGeneration);
        fbb.addInt64(4, object.importedAt?.millisecondsSinceEpoch);
        fbb.addInt64(5, object.chunkCount);
        fbb.addInt64(6, object.nodeCount);
        fbb.addInt64(7, object.edgeCount);
        fbb.addOffset(8, readinessStateOffset);
        fbb.addOffset(9, lastErrorOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final importedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sourceHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final schemaVersionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final activeGenerationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final importedAtParam = importedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(importedAtValue, isUtc: true);
        final chunkCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final nodeCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final edgeCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final readinessStateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final lastErrorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = RouteGraphManifest(
          id: idParam,
          sourceHash: sourceHashParam,
          schemaVersion: schemaVersionParam,
          activeGeneration: activeGenerationParam,
          importedAt: importedAtParam,
          chunkCount: chunkCountParam,
          nodeCount: nodeCountParam,
          edgeCount: edgeCountParam,
          readinessState: readinessStateParam,
          lastError: lastErrorParam,
        );

        return object;
      },
    ),
    RouteGraphWayIndex: obx_int.EntityDefinition<RouteGraphWayIndex>(
      model: _entities[8],
      toOneRelations: (RouteGraphWayIndex object) => [],
      toManyRelations: (RouteGraphWayIndex object) => {},
      getId: (RouteGraphWayIndex object) => object.id,
      setId: (RouteGraphWayIndex object, int id) {
        object.id = id;
      },
      objectToFB: (RouteGraphWayIndex object, fb.Builder fbb) {
        final recordKeyOffset = fbb.writeString(object.recordKey);
        final chunkKeyOffset = fbb.writeString(object.chunkKey);
        final highwayOffset = object.highway == null
            ? null
            : fbb.writeString(object.highway!);
        final surfaceOffset = object.surface == null
            ? null
            : fbb.writeString(object.surface!);
        final footwayOffset = object.footway == null
            ? null
            : fbb.writeString(object.footway!);
        final footOffset = object.foot == null
            ? null
            : fbb.writeString(object.foot!);
        final routeOffset = object.route == null
            ? null
            : fbb.writeString(object.route!);
        final accessOffset = object.access == null
            ? null
            : fbb.writeString(object.access!);
        final nameOffset = object.name == null
            ? null
            : fbb.writeString(object.name!);
        final normalizedNameOffset = object.normalizedName == null
            ? null
            : fbb.writeString(object.normalizedName!);
        final tagsJsonOffset = fbb.writeString(object.tagsJson);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, recordKeyOffset);
        fbb.addInt64(2, object.generation);
        fbb.addOffset(3, chunkKeyOffset);
        fbb.addInt64(4, object.osmWayId);
        fbb.addOffset(5, highwayOffset);
        fbb.addOffset(6, surfaceOffset);
        fbb.addOffset(7, footwayOffset);
        fbb.addOffset(8, footOffset);
        fbb.addOffset(9, routeOffset);
        fbb.addOffset(10, accessOffset);
        fbb.addOffset(11, nameOffset);
        fbb.addOffset(12, normalizedNameOffset);
        fbb.addInt64(13, object.lengthMeters);
        fbb.addInt64(14, object.tagCount);
        fbb.addOffset(15, tagsJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final recordKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final generationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final chunkKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final osmWayIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final highwayParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final surfaceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final footwayParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final footParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final routeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final accessParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final normalizedNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final lengthMetersParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final tagCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final tagsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final object = RouteGraphWayIndex(
          id: idParam,
          recordKey: recordKeyParam,
          generation: generationParam,
          chunkKey: chunkKeyParam,
          osmWayId: osmWayIdParam,
          highway: highwayParam,
          surface: surfaceParam,
          footway: footwayParam,
          foot: footParam,
          route: routeParam,
          access: accessParam,
          name: nameParam,
          normalizedName: normalizedNameParam,
          lengthMeters: lengthMetersParam,
          tagCount: tagCountParam,
          tagsJson: tagsJsonParam,
        );

        return object;
      },
    ),
    RouteGraphTrailDisplayChunk:
        obx_int.EntityDefinition<RouteGraphTrailDisplayChunk>(
          model: _entities[9],
          toOneRelations: (RouteGraphTrailDisplayChunk object) => [],
          toManyRelations: (RouteGraphTrailDisplayChunk object) => {},
          getId: (RouteGraphTrailDisplayChunk object) => object.id,
          setId: (RouteGraphTrailDisplayChunk object, int id) {
            object.id = id;
          },
          objectToFB: (RouteGraphTrailDisplayChunk object, fb.Builder fbb) {
            final recordKeyOffset = fbb.writeString(object.recordKey);
            final chunkKeyOffset = fbb.writeString(object.chunkKey);
            final payloadJsonOffset = fbb.writeString(object.payloadJson);
            fbb.startTable(7);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, recordKeyOffset);
            fbb.addInt64(2, object.generation);
            fbb.addInt64(3, object.cacheZoom);
            fbb.addOffset(4, chunkKeyOffset);
            fbb.addOffset(5, payloadJsonOffset);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final idParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              4,
              0,
            );
            final recordKeyParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final generationParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              8,
              0,
            );
            final cacheZoomParam = const fb.Int64Reader().vTableGet(
              buffer,
              rootOffset,
              10,
              0,
            );
            final chunkKeyParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 12, '');
            final payloadJsonParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 14, '');
            final object = RouteGraphTrailDisplayChunk(
              id: idParam,
              recordKey: recordKeyParam,
              generation: generationParam,
              cacheZoom: cacheZoomParam,
              chunkKey: chunkKeyParam,
              payloadJson: payloadJsonParam,
            );

            return object;
          },
        ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Peak] entity fields to define ObjectBox queries.
class Peak_ {
  /// See [Peak.id].
  static final id = obx.QueryIntegerProperty<Peak>(_entities[0].properties[0]);

  /// See [Peak.name].
  static final name = obx.QueryStringProperty<Peak>(_entities[0].properties[1]);

  /// See [Peak.elevation].
  static final elevation = obx.QueryDoubleProperty<Peak>(
    _entities[0].properties[2],
  );

  /// See [Peak.latitude].
  static final latitude = obx.QueryDoubleProperty<Peak>(
    _entities[0].properties[3],
  );

  /// See [Peak.longitude].
  static final longitude = obx.QueryDoubleProperty<Peak>(
    _entities[0].properties[4],
  );

  /// See [Peak.region].
  static final region = obx.QueryStringProperty<Peak>(
    _entities[0].properties[5],
  );

  /// See [Peak.gridZoneDesignator].
  static final gridZoneDesignator = obx.QueryStringProperty<Peak>(
    _entities[0].properties[6],
  );

  /// See [Peak.mgrs100kId].
  static final mgrs100kId = obx.QueryStringProperty<Peak>(
    _entities[0].properties[7],
  );

  /// See [Peak.easting].
  static final easting = obx.QueryStringProperty<Peak>(
    _entities[0].properties[8],
  );

  /// See [Peak.northing].
  static final northing = obx.QueryStringProperty<Peak>(
    _entities[0].properties[9],
  );

  /// See [Peak.osmId].
  static final osmId = obx.QueryIntegerProperty<Peak>(
    _entities[0].properties[10],
  );

  /// See [Peak.sourceOfTruth].
  static final sourceOfTruth = obx.QueryStringProperty<Peak>(
    _entities[0].properties[11],
  );

  /// See [Peak.altName].
  static final altName = obx.QueryStringProperty<Peak>(
    _entities[0].properties[12],
  );

  /// See [Peak.verified].
  static final verified = obx.QueryBooleanProperty<Peak>(
    _entities[0].properties[13],
  );

  /// See [Peak.peakbaggerPid].
  static final peakbaggerPid = obx.QueryIntegerProperty<Peak>(
    _entities[0].properties[14],
  );

  /// See [Peak.prominence].
  static final prominence = obx.QueryDoubleProperty<Peak>(
    _entities[0].properties[15],
  );

  /// See [Peak.country].
  static final country = obx.QueryStringProperty<Peak>(
    _entities[0].properties[16],
  );

  /// See [Peak.county].
  static final county = obx.QueryStringProperty<Peak>(
    _entities[0].properties[17],
  );

  /// See [Peak.range].
  static final range = obx.QueryStringProperty<Peak>(
    _entities[0].properties[18],
  );
}

/// [Tasmap50k] entity fields to define ObjectBox queries.
class Tasmap50k_ {
  /// See [Tasmap50k.id].
  static final id = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[0],
  );

  /// See [Tasmap50k.series].
  static final series = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[1],
  );

  /// See [Tasmap50k.name].
  static final name = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[2],
  );

  /// See [Tasmap50k.parentSeries].
  static final parentSeries = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[3],
  );

  /// See [Tasmap50k.mgrs100kIds].
  static final mgrs100kIds = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[4],
  );

  /// See [Tasmap50k.eastingMin].
  static final eastingMin = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[5],
  );

  /// See [Tasmap50k.eastingMax].
  static final eastingMax = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[6],
  );

  /// See [Tasmap50k.northingMin].
  static final northingMin = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[7],
  );

  /// See [Tasmap50k.northingMax].
  static final northingMax = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[8],
  );

  /// See [Tasmap50k.mgrsMid].
  static final mgrsMid = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[9],
  );

  /// See [Tasmap50k.eastingMid].
  static final eastingMid = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[10],
  );

  /// See [Tasmap50k.northingMid].
  static final northingMid = obx.QueryIntegerProperty<Tasmap50k>(
    _entities[1].properties[11],
  );

  /// See [Tasmap50k.p1].
  static final p1 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[12],
  );

  /// See [Tasmap50k.p2].
  static final p2 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[13],
  );

  /// See [Tasmap50k.p3].
  static final p3 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[14],
  );

  /// See [Tasmap50k.p4].
  static final p4 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[15],
  );

  /// See [Tasmap50k.p5].
  static final p5 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[16],
  );

  /// See [Tasmap50k.p6].
  static final p6 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[17],
  );

  /// See [Tasmap50k.p7].
  static final p7 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[18],
  );

  /// See [Tasmap50k.p8].
  static final p8 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[19],
  );

  /// See [Tasmap50k.p9].
  static final p9 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[20],
  );

  /// See [Tasmap50k.p10].
  static final p10 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[21],
  );

  /// See [Tasmap50k.p11].
  static final p11 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[22],
  );

  /// See [Tasmap50k.p12].
  static final p12 = obx.QueryStringProperty<Tasmap50k>(
    _entities[1].properties[23],
  );
}

/// [GpxTrack] entity fields to define ObjectBox queries.
class GpxTrack_ {
  /// See [GpxTrack.gpxTrackId].
  static final gpxTrackId = obx.QueryIntegerProperty<GpxTrack>(
    _entities[2].properties[0],
  );

  /// See [GpxTrack.trackName].
  static final trackName = obx.QueryStringProperty<GpxTrack>(
    _entities[2].properties[1],
  );

  /// See [GpxTrack.startDateTime].
  static final startDateTime = obx.QueryDateProperty<GpxTrack>(
    _entities[2].properties[2],
  );

  /// See [GpxTrack.ascent].
  static final ascent = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[3],
  );

  /// See [GpxTrack.totalTimeMillis].
  static final totalTimeMillis = obx.QueryIntegerProperty<GpxTrack>(
    _entities[2].properties[4],
  );

  /// See [GpxTrack.trackColour].
  static final trackColour = obx.QueryIntegerProperty<GpxTrack>(
    _entities[2].properties[5],
  );

  /// See [GpxTrack.contentHash].
  static final contentHash = obx.QueryStringProperty<GpxTrack>(
    _entities[2].properties[6],
  );

  /// See [GpxTrack.trackDate].
  static final trackDate = obx.QueryDateProperty<GpxTrack>(
    _entities[2].properties[7],
  );

  /// See [GpxTrack.endDateTime].
  static final endDateTime = obx.QueryDateProperty<GpxTrack>(
    _entities[2].properties[8],
  );

  /// See [GpxTrack.gpxFile].
  static final gpxFile = obx.QueryStringProperty<GpxTrack>(
    _entities[2].properties[9],
  );

  /// See [GpxTrack.displayTrackPointsByZoom].
  static final displayTrackPointsByZoom = obx.QueryStringProperty<GpxTrack>(
    _entities[2].properties[10],
  );

  /// See [GpxTrack.distanceToPeak].
  static final distanceToPeak = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[11],
  );

  /// See [GpxTrack.distanceFromPeak].
  static final distanceFromPeak = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[12],
  );

  /// See [GpxTrack.lowestElevation].
  static final lowestElevation = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[13],
  );

  /// See [GpxTrack.highestElevation].
  static final highestElevation = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[14],
  );

  /// See [GpxTrack.distance2d].
  static final distance2d = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[15],
  );

  /// See [GpxTrack.distance3d].
  static final distance3d = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[16],
  );

  /// See [GpxTrack.descent].
  static final descent = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[17],
  );

  /// See [GpxTrack.startElevation].
  static final startElevation = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[18],
  );

  /// See [GpxTrack.endElevation].
  static final endElevation = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[19],
  );

  /// See [GpxTrack.elevationProfile].
  static final elevationProfile = obx.QueryStringProperty<GpxTrack>(
    _entities[2].properties[20],
  );

  /// See [GpxTrack.filteredTrack].
  static final filteredTrack = obx.QueryStringProperty<GpxTrack>(
    _entities[2].properties[21],
  );

  /// See [GpxTrack.peakCorrelationProcessed].
  static final peakCorrelationProcessed = obx.QueryBooleanProperty<GpxTrack>(
    _entities[2].properties[22],
  );

  /// See [GpxTrack.movingTime].
  static final movingTime = obx.QueryIntegerProperty<GpxTrack>(
    _entities[2].properties[23],
  );

  /// See [GpxTrack.restingTime].
  static final restingTime = obx.QueryIntegerProperty<GpxTrack>(
    _entities[2].properties[24],
  );

  /// See [GpxTrack.pausedTime].
  static final pausedTime = obx.QueryIntegerProperty<GpxTrack>(
    _entities[2].properties[25],
  );

  /// See [GpxTrack.gpxFileRepaired].
  static final gpxFileRepaired = obx.QueryStringProperty<GpxTrack>(
    _entities[2].properties[26],
  );

  /// See [GpxTrack.visible].
  static final visible = obx.QueryBooleanProperty<GpxTrack>(
    _entities[2].properties[27],
  );

  /// See [GpxTrack.averageSpeedKmh].
  static final averageSpeedKmh = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[28],
  );

  /// See [GpxTrack.movingSpeedKmh].
  static final movingSpeedKmh = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[29],
  );

  /// See [GpxTrack.maxSpeedKmh].
  static final maxSpeedKmh = obx.QueryDoubleProperty<GpxTrack>(
    _entities[2].properties[30],
  );

  /// see [GpxTrack.peaks]
  static final peaks = obx.QueryRelationToMany<GpxTrack, Peak>(
    _entities[2].relations[0],
  );
}

/// [PeakList] entity fields to define ObjectBox queries.
class PeakList_ {
  /// See [PeakList.peakListId].
  static final peakListId = obx.QueryIntegerProperty<PeakList>(
    _entities[3].properties[0],
  );

  /// See [PeakList.name].
  static final name = obx.QueryStringProperty<PeakList>(
    _entities[3].properties[1],
  );

  /// See [PeakList.peakList].
  static final peakList = obx.QueryStringProperty<PeakList>(
    _entities[3].properties[2],
  );

  /// See [PeakList.region].
  static final region = obx.QueryStringProperty<PeakList>(
    _entities[3].properties[3],
  );
}

/// [PeaksBagged] entity fields to define ObjectBox queries.
class PeaksBagged_ {
  /// See [PeaksBagged.baggedId].
  static final baggedId = obx.QueryIntegerProperty<PeaksBagged>(
    _entities[4].properties[0],
  );

  /// See [PeaksBagged.peakId].
  static final peakId = obx.QueryIntegerProperty<PeaksBagged>(
    _entities[4].properties[1],
  );

  /// See [PeaksBagged.gpxId].
  static final gpxId = obx.QueryIntegerProperty<PeaksBagged>(
    _entities[4].properties[2],
  );

  /// See [PeaksBagged.date].
  static final date = obx.QueryDateProperty<PeaksBagged>(
    _entities[4].properties[3],
  );
}

/// [Route] entity fields to define ObjectBox queries.
class Route_ {
  /// See [Route.id].
  static final id = obx.QueryIntegerProperty<Route>(_entities[5].properties[0]);

  /// See [Route.name].
  static final name = obx.QueryStringProperty<Route>(
    _entities[5].properties[1],
  );

  /// See [Route.displayRoutePointsByZoom].
  static final displayRoutePointsByZoom = obx.QueryStringProperty<Route>(
    _entities[5].properties[2],
  );

  /// See [Route.colour].
  static final colour = obx.QueryIntegerProperty<Route>(
    _entities[5].properties[3],
  );

  /// See [Route.distance2d].
  static final distance2d = obx.QueryDoubleProperty<Route>(
    _entities[5].properties[4],
  );

  /// See [Route.distance3d].
  static final distance3d = obx.QueryDoubleProperty<Route>(
    _entities[5].properties[5],
  );

  /// See [Route.ascent].
  static final ascent = obx.QueryDoubleProperty<Route>(
    _entities[5].properties[6],
  );

  /// See [Route.descent].
  static final descent = obx.QueryDoubleProperty<Route>(
    _entities[5].properties[7],
  );

  /// See [Route.startElevation].
  static final startElevation = obx.QueryDoubleProperty<Route>(
    _entities[5].properties[8],
  );

  /// See [Route.endElevation].
  static final endElevation = obx.QueryDoubleProperty<Route>(
    _entities[5].properties[9],
  );

  /// See [Route.lowestElevation].
  static final lowestElevation = obx.QueryDoubleProperty<Route>(
    _entities[5].properties[10],
  );

  /// See [Route.highestElevation].
  static final highestElevation = obx.QueryDoubleProperty<Route>(
    _entities[5].properties[11],
  );

  /// See [Route.gpxRouteJson].
  static final gpxRouteJson = obx.QueryStringProperty<Route>(
    _entities[5].properties[12],
  );

  /// See [Route.routeWaypointsJson].
  static final routeWaypointsJson = obx.QueryStringProperty<Route>(
    _entities[5].properties[13],
  );

  /// See [Route.desc].
  static final desc = obx.QueryStringProperty<Route>(
    _entities[5].properties[14],
  );

  /// See [Route.visible].
  static final visible = obx.QueryBooleanProperty<Route>(
    _entities[5].properties[15],
  );
}

/// [RouteGraphChunk] entity fields to define ObjectBox queries.
class RouteGraphChunk_ {
  /// See [RouteGraphChunk.id].
  static final id = obx.QueryIntegerProperty<RouteGraphChunk>(
    _entities[6].properties[0],
  );

  /// See [RouteGraphChunk.recordKey].
  static final recordKey = obx.QueryStringProperty<RouteGraphChunk>(
    _entities[6].properties[1],
  );

  /// See [RouteGraphChunk.chunkKey].
  static final chunkKey = obx.QueryStringProperty<RouteGraphChunk>(
    _entities[6].properties[2],
  );

  /// See [RouteGraphChunk.generation].
  static final generation = obx.QueryIntegerProperty<RouteGraphChunk>(
    _entities[6].properties[3],
  );

  /// See [RouteGraphChunk.minLat].
  static final minLat = obx.QueryDoubleProperty<RouteGraphChunk>(
    _entities[6].properties[4],
  );

  /// See [RouteGraphChunk.minLon].
  static final minLon = obx.QueryDoubleProperty<RouteGraphChunk>(
    _entities[6].properties[5],
  );

  /// See [RouteGraphChunk.maxLat].
  static final maxLat = obx.QueryDoubleProperty<RouteGraphChunk>(
    _entities[6].properties[6],
  );

  /// See [RouteGraphChunk.maxLon].
  static final maxLon = obx.QueryDoubleProperty<RouteGraphChunk>(
    _entities[6].properties[7],
  );

  /// See [RouteGraphChunk.elementCount].
  static final elementCount = obx.QueryIntegerProperty<RouteGraphChunk>(
    _entities[6].properties[8],
  );

  /// See [RouteGraphChunk.payloadJson].
  static final payloadJson = obx.QueryStringProperty<RouteGraphChunk>(
    _entities[6].properties[9],
  );
}

/// [RouteGraphManifest] entity fields to define ObjectBox queries.
class RouteGraphManifest_ {
  /// See [RouteGraphManifest.id].
  static final id = obx.QueryIntegerProperty<RouteGraphManifest>(
    _entities[7].properties[0],
  );

  /// See [RouteGraphManifest.sourceHash].
  static final sourceHash = obx.QueryStringProperty<RouteGraphManifest>(
    _entities[7].properties[1],
  );

  /// See [RouteGraphManifest.schemaVersion].
  static final schemaVersion = obx.QueryStringProperty<RouteGraphManifest>(
    _entities[7].properties[2],
  );

  /// See [RouteGraphManifest.activeGeneration].
  static final activeGeneration = obx.QueryIntegerProperty<RouteGraphManifest>(
    _entities[7].properties[3],
  );

  /// See [RouteGraphManifest.importedAt].
  static final importedAt = obx.QueryDateProperty<RouteGraphManifest>(
    _entities[7].properties[4],
  );

  /// See [RouteGraphManifest.chunkCount].
  static final chunkCount = obx.QueryIntegerProperty<RouteGraphManifest>(
    _entities[7].properties[5],
  );

  /// See [RouteGraphManifest.nodeCount].
  static final nodeCount = obx.QueryIntegerProperty<RouteGraphManifest>(
    _entities[7].properties[6],
  );

  /// See [RouteGraphManifest.edgeCount].
  static final edgeCount = obx.QueryIntegerProperty<RouteGraphManifest>(
    _entities[7].properties[7],
  );

  /// See [RouteGraphManifest.readinessState].
  static final readinessState = obx.QueryStringProperty<RouteGraphManifest>(
    _entities[7].properties[8],
  );

  /// See [RouteGraphManifest.lastError].
  static final lastError = obx.QueryStringProperty<RouteGraphManifest>(
    _entities[7].properties[9],
  );
}

/// [RouteGraphWayIndex] entity fields to define ObjectBox queries.
class RouteGraphWayIndex_ {
  /// See [RouteGraphWayIndex.id].
  static final id = obx.QueryIntegerProperty<RouteGraphWayIndex>(
    _entities[8].properties[0],
  );

  /// See [RouteGraphWayIndex.recordKey].
  static final recordKey = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[1],
  );

  /// See [RouteGraphWayIndex.generation].
  static final generation = obx.QueryIntegerProperty<RouteGraphWayIndex>(
    _entities[8].properties[2],
  );

  /// See [RouteGraphWayIndex.chunkKey].
  static final chunkKey = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[3],
  );

  /// See [RouteGraphWayIndex.osmWayId].
  static final osmWayId = obx.QueryIntegerProperty<RouteGraphWayIndex>(
    _entities[8].properties[4],
  );

  /// See [RouteGraphWayIndex.highway].
  static final highway = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[5],
  );

  /// See [RouteGraphWayIndex.surface].
  static final surface = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[6],
  );

  /// See [RouteGraphWayIndex.footway].
  static final footway = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[7],
  );

  /// See [RouteGraphWayIndex.foot].
  static final foot = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[8],
  );

  /// See [RouteGraphWayIndex.route].
  static final route = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[9],
  );

  /// See [RouteGraphWayIndex.access].
  static final access = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[10],
  );

  /// See [RouteGraphWayIndex.name].
  static final name = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[11],
  );

  /// See [RouteGraphWayIndex.normalizedName].
  static final normalizedName = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[12],
  );

  /// See [RouteGraphWayIndex.lengthMeters].
  static final lengthMeters = obx.QueryIntegerProperty<RouteGraphWayIndex>(
    _entities[8].properties[13],
  );

  /// See [RouteGraphWayIndex.tagCount].
  static final tagCount = obx.QueryIntegerProperty<RouteGraphWayIndex>(
    _entities[8].properties[14],
  );

  /// See [RouteGraphWayIndex.tagsJson].
  static final tagsJson = obx.QueryStringProperty<RouteGraphWayIndex>(
    _entities[8].properties[15],
  );
}

/// [RouteGraphTrailDisplayChunk] entity fields to define ObjectBox queries.
class RouteGraphTrailDisplayChunk_ {
  /// See [RouteGraphTrailDisplayChunk.id].
  static final id = obx.QueryIntegerProperty<RouteGraphTrailDisplayChunk>(
    _entities[9].properties[0],
  );

  /// See [RouteGraphTrailDisplayChunk.recordKey].
  static final recordKey = obx.QueryStringProperty<RouteGraphTrailDisplayChunk>(
    _entities[9].properties[1],
  );

  /// See [RouteGraphTrailDisplayChunk.generation].
  static final generation =
      obx.QueryIntegerProperty<RouteGraphTrailDisplayChunk>(
        _entities[9].properties[2],
      );

  /// See [RouteGraphTrailDisplayChunk.cacheZoom].
  static final cacheZoom =
      obx.QueryIntegerProperty<RouteGraphTrailDisplayChunk>(
        _entities[9].properties[3],
      );

  /// See [RouteGraphTrailDisplayChunk.chunkKey].
  static final chunkKey = obx.QueryStringProperty<RouteGraphTrailDisplayChunk>(
    _entities[9].properties[4],
  );

  /// See [RouteGraphTrailDisplayChunk.payloadJson].
  static final payloadJson =
      obx.QueryStringProperty<RouteGraphTrailDisplayChunk>(
        _entities[9].properties[5],
      );
}
