ServerName tiles.peakbagger.com

Listen 443

<VirtualHost *:443>
    ServerName tiles.peakbagger.com

    SSLEngine on
    SSLCertificateFile "/Users/adrian/Development/mapping/peak_bagger/proxy/slovenia-topo-proxy/local-production/certs/tiles.peakbagger.com.pem"
    SSLCertificateKeyFile "/Users/adrian/Development/mapping/peak_bagger/proxy/slovenia-topo-proxy/local-production/certs/tiles.peakbagger.com-key.pem"

    ProxyPreserveHost On
    SSLProxyEngine On

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "tiles.peakbagger.com"

    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/

    ErrorLog "/private/var/log/apache2/tiles.peakbagger.com-error.log"
    CustomLog "/private/var/log/apache2/tiles.peakbagger.com-access.log" combined
</VirtualHost>
